### PR TITLE
Proposed mobile-friendly tip for images tutorial

### PR DESCRIPTION
**Pull request by brewerj**
Proposed new tip ("Responsive design") to improve coverage for responsive design of images. 

If confirmed, add note "Developed with support from WCAG TA Project"

### CODE REVIEW

**Comment by yatil** [comment]
I like it!

**Review by iamjolly — COMMENTED** [review]
This is good information. I stumbled a bit over the use of "drop" in:

> On smaller screens, icons often _drop_ text labels.

Would it be any better if we say:

> On smaller screens, icons often _replace_ text labels.

? 

Emphasis on either "drop" or "replace" would not be needed on production pages.

**Comment by bakkenb** [comment]
> This is good information. I stumbled a bit over the use of "drop" in:
>
>    "On smaller screens, icons often drop text labels."
>
>Would it be any better if we say:
>
>   "On smaller screens, icons often replace text labels."

The way I read the original tip is that if there is an icon WITH text, then on a small screen sometimes the text is automatically dropped and only the icon is left. I don't think "replace" would be correct if that is what is being described here. If so maybe...

> Icons with text labels will often drop the text labels when viewed on smaller screens. Ensure that icons are readable at that size, understandable without text, and have text descriptions.

**Review by hkramer — COMMENTED** [review]
I'm okay with the version presented here or with Brent's version.

**Comment by yatil** [comment]
I added the tip to the new-style images tutorial here (the tutorials are split in new repositories to make issue traversal easier). I’ll close this Pull Request once the change is approved by EOWG. 
https://wai-tutorial-images.netlify.com/tutorials/images/tips/

**Review by bakkenb — APPROVED** [review]
Looks good to me.

**Comment by yatil** [comment]
This has been merged in when we moved to the new layout. (I would close the issue, but I’m powerless.)

**Comment by brianelton** [comment]
This change appears to be in the current version, so am closing the PR

**Pull request closed without merging**
