### PR TITLE
Updates to tutorials

### PR DESCRIPTION
**Pull request by brianelton**
Fixes for #689 and #546, plus update to meta footer, acknowledgements

### CODE REVIEW

**Comment by brianelton** [comment]
@shawna-slh I have merged your PR to remove (s)

**Comment by brianelton** [comment]
@shawna-slh a few updates have been made to this PR. I will not be doing any more before publishing unless necessary.

**Comment by shawna-slh** [comment]
Published. Please QA check. Thanks!

**Comment by brianelton** [comment]
QA'd and all looks good!

**Pull request merged**
