### PR TITLE
Site Navigation → Menus

### LINKED ISSUE #407: Menus - Fly-out Menus - for dexterity
Some people have trouble operating fly-out menus, especially people with tremors, limited fine motor dexterity, etc. (disclosure: including myself)

Is there any reason not to suggest that menus are available in a non-fly-out option -- that is, if one clicks on the top menu item, it goes to a page with all the sub-links not-fly-out?

### LINKED ISSUE #413: Fly-out menus: Mention dropdown menus
@shwetank commented on issue https://github.com/w3c/wai-tutorials/issues/407#issuecomment-277176801

> Regarding "fly-out" menus : The more prevalent term I have heard is "drop-down" menus, so maybe we could mention that term here too? Just for some extra clarity.

### LINKED ISSUE #419: [Navigation] disagree with current approach
The current approach has been discussed at the [November face-to-face](https://www.w3.org/WAI/EO/wiki/EOWG_F2F_November_2016/Tutorial_Discussion#Meeting_Outcomes) and on the [December 16th call](https://www.w3.org/2016/12/16-eo-minutes.html#item04). Yet as presented today, I feel that the Navigation tutorial seems unfocused and messy. I suggest changing this tutorial from "Navigation" to focus on "Menus" only - the rest can mostly fit into the "Page Structure" tutorial fairly well. Specifically:

1. **Move the "Anchors" section into the "Page Structure" tutorial**: Currently this section consists of two paragraphs - one explaining how URLs work, which I think should be dropped or reduced to one sentence, and another that basically says "add anchors so that people can bookmark and skip to them". I think this can be easily added somewhere to the "Page Structure" tutorial, such as in the "Headings", "Page Regions", and/or "Tips and Tricks" sections.
2. **Move "Skip Links" section into the "Page Structure tutorial**: Currently this section describes adding a list-type widget/component to pages, to help people skip to the relevant sections of a page. Again, this seems to fit well within the "Page Structure" tutorial, either as a new section or somewhere else in there.
3. **Move "Table of Content" section into the "Page Structure tutorial**: Again, also this seems to me to  be a page widget/component that can be easily fitted into the "Page Structure" tutorial, for example in a "Tips and Tricks" section there.
4. **Describe "Breadcrumbs" as a type of "Menu"**: This section can be kept in the new "Menus" tutorial. It follows the current approach of "structure - styling - content" quite well.
5. **Move "Sitemap" section to a "Tips and Tricks" section**: Currently this is a very short section and can fit easily in a "Tips and Tricks" section of the tutorial. Actually I don't even think this is a high-priority issue and we could even drop this for now, if it doesn't fit any of the tutorials.
6. **Keep "Search" as currently is in the "Page Structure" tutorial**. We already have a "Search" section in the "Page Structure" tutorial, and it would be good to avoid repetition, The suggested focus on "Menus" would help streamline the two tutorials and reduce repetition.

Side note: This comment is on the overall approach and not on the wording. I think the wording can be tightened up and made clearer. Also, I offered to Eric making pull requests with these suggestions but he wanted to check with the group first.

### PR DESCRIPTION
**Pull request by yatil**
**Replaces #415**

Fixes #419.
Fixes #413 (was already addressed in PR #415).
Fixes #407 (was already addressed in PR #415).

### CODE REVIEW

**Comment by nitedog** [comment]
I suggest adding two new pages to the tutorial:
- "Example Menu 1": full example and code of the navigation menu shown throughout
- "Example Menu 2": full example and code of the application menu (current "Web App Menu Code")

**Comment by yatil** [comment]
I prefer the examples mixed with the tutorial text. This is the standard tutorial format (it is what a tutorial is in comparison to an article with attached examples). Removing them makes them less useful from my point of view.

**Comment by nitedog** [comment]
In this case, because the menus take little space, I support keeping them inline. I think I kept most examples that really showed something (like with and without button for sub-menus).

But another use case is someone coming to the tutorial looking for the complete code and example to copy and start working from - putting it on a separate page (as we have for the carousel) could be useful too IMO.

**Comment by yatil** [comment]
I am profoundly worried about this potentially blurring the line more between the App Menus and the Page Menus, leading to mixup between them. I’ll take a more in-depth look at your suggestions when I’m back working on the project on Wednesday.

**Pull request merged**
